import {
  Customer,
  Quotation,
  Order,
  InventoryItem,
  Machine,
  Worker,
  Supplier,
  PurchaseOrder,
  Invoice,
  ActivityLog,
  NotificationItem,
  DashboardMetrics,
} from '@/types';

export const INITIAL_METRICS: DashboardMetrics = {
  totalOrders: 148,
  ordersTrendPercent: 12.4,
  pendingQuotations: 23,
  quotationsTrendPercent: 8.1,
  activeProductionJobs: 18,
  jobsTrendPercent: 5.2,
  lowInventoryAlerts: 4,
  revenue: 342850,
  revenueTrendPercent: 14.8,
  pendingPayments: 48500,
  overduePaymentsCount: 3,
};

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    companyName: 'Apex Aerospace Solutions',
    contactName: 'Robert Vance',
    email: 'rvance@apexaero.com',
    phone: '+1 (555) 234-8901',
    industry: 'Aerospace & Defense',
    address: '1040 Turbine Way, Seattle, WA',
    status: 'Active',
    totalOrders: 34,
    lifetimeValue: 284500,
    createdAt: '2024-01-15',
  },
  {
    id: 'cust-2',
    companyName: 'Titan Heavy Machinery',
    contactName: 'Sarah Jenkins',
    email: 'sjenkins@titanheavy.com',
    phone: '+1 (555) 876-1234',
    industry: 'Heavy Equipment',
    address: '88 Industrial Pkwy, Cleveland, OH',
    status: 'Active',
    totalOrders: 19,
    lifetimeValue: 195400,
    createdAt: '2024-02-04',
  },
  {
    id: 'cust-3',
    companyName: 'Vanguard Enclosures Inc.',
    contactName: 'Marcus Sterling',
    email: 'msterling@vanguard.com',
    phone: '+1 (555) 432-9081',
    industry: 'Electronics Enclosures',
    address: '450 Tech Loop, Austin, TX',
    status: 'Active',
    totalOrders: 42,
    lifetimeValue: 312000,
    createdAt: '2023-11-20',
  },
  {
    id: 'cust-4',
    companyName: 'Precision HVAC Systems',
    contactName: 'David Miller',
    email: 'dmiller@precisionhvac.com',
    phone: '+1 (555) 654-3210',
    industry: 'HVAC Fabrication',
    address: '302 Commerce St, Chicago, IL',
    status: 'Active',
    totalOrders: 15,
    lifetimeValue: 98000,
    createdAt: '2024-03-10',
  },
  {
    id: 'cust-5',
    companyName: 'Nexus Renewable Energy',
    contactName: 'Elena Rostova',
    email: 'elena@nexusenergy.io',
    phone: '+1 (555) 987-6543',
    industry: 'Solar & CleanTech',
    address: '72 Solar Blvd, San Jose, CA',
    status: 'Lead',
    totalOrders: 3,
    lifetimeValue: 45000,
    createdAt: '2024-05-18',
  },
  {
    id: 'cust-6',
    companyName: 'Stallion Architectural Metals',
    contactName: 'Gary Thorne',
    email: 'gthorne@stallionmetal.com',
    phone: '+1 (555) 321-7654',
    industry: 'Architectural Sheet Metal',
    address: '119 Metalwork Ave, Denver, CO',
    status: 'Inactive',
    totalOrders: 8,
    lifetimeValue: 62000,
    createdAt: '2023-08-11',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'WO-2026-0891',
    customerId: 'cust-1',
    customerName: 'Apex Aerospace Solutions',
    title: 'Laser Cut Titanium Duct Flanges',
    priority: 'Rush',
    status: 'In Production',
    progressPercent: 68,
    totalAmount: 42500,
    dueDate: '2026-08-15',
    createdAt: '2026-08-01',
  },
  {
    id: 'ord-102',
    orderNumber: 'WO-2026-0892',
    customerId: 'cust-3',
    customerName: 'Vanguard Enclosures Inc.',
    title: 'NEMA 4X Stainless Steel Electrical Cabinets',
    priority: 'High',
    status: 'Quality Check',
    progressPercent: 92,
    totalAmount: 28900,
    dueDate: '2026-08-10',
    createdAt: '2026-07-28',
  },
  {
    id: 'ord-103',
    orderNumber: 'WO-2026-0893',
    customerId: 'cust-2',
    customerName: 'Titan Heavy Machinery',
    title: 'Heavy Gauge Excavator Bucket Liners',
    priority: 'Normal',
    status: 'In Production',
    progressPercent: 45,
    totalAmount: 54000,
    dueDate: '2026-08-22',
    createdAt: '2026-08-03',
  },
  {
    id: 'ord-104',
    orderNumber: 'WO-2026-0894',
    customerId: 'cust-4',
    customerName: 'Precision HVAC Systems',
    title: 'Galvanized Air Handling Transition Boxes',
    priority: 'Normal',
    status: 'Pending',
    progressPercent: 10,
    totalAmount: 14200,
    dueDate: '2026-08-28',
    createdAt: '2026-08-05',
  },
  {
    id: 'ord-105',
    orderNumber: 'WO-2026-0895',
    customerId: 'cust-5',
    customerName: 'Nexus Renewable Energy',
    title: 'Aluminum Solar Tracker Bracket Assemblies',
    priority: 'High',
    status: 'Ready for Shipping',
    progressPercent: 98,
    totalAmount: 36000,
    dueDate: '2026-08-08',
    createdAt: '2026-07-20',
  },
  {
    id: 'ord-106',
    orderNumber: 'WO-2026-0890',
    customerId: 'cust-1',
    customerName: 'Apex Aerospace Solutions',
    title: 'High-Precision Jet Engine Mounting Plates',
    priority: 'Rush',
    status: 'Completed',
    progressPercent: 100,
    totalAmount: 78000,
    dueDate: '2026-08-02',
    createdAt: '2026-07-15',
  },
];

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'qt-201',
    quotationNumber: 'RFQ-2026-0412',
    customerId: 'cust-1',
    customerName: 'Apex Aerospace Solutions',
    title: 'Batch 500 Avionics Heat Sink Plates',
    status: 'Sent',
    totalAmount: 31500,
    validUntil: '2026-08-25',
    createdAt: '2026-08-04',
    lineItems: [
      { id: 'li-1', partName: 'Heat Sink Base', material: '6061-T6 Aluminum', thickness: '6mm', quantity: 500, unitPrice: 45, totalPrice: 22500 },
      { id: 'li-2', partName: 'Mounting Bracket', material: '304 Stainless', thickness: '2mm', quantity: 500, unitPrice: 18, totalPrice: 9000 },
    ],
  },
  {
    id: 'qt-202',
    quotationNumber: 'RFQ-2026-0413',
    customerId: 'cust-2',
    customerName: 'Titan Heavy Machinery',
    title: 'CNC Formed Chassis Support Ribs',
    status: 'Approved',
    totalAmount: 64200,
    validUntil: '2026-08-30',
    createdAt: '2026-08-02',
    lineItems: [
      { id: 'li-3', partName: 'Chassis Support Plate', material: 'A36 Structural Steel', thickness: '12mm', quantity: 200, unitPrice: 321, totalPrice: 64200 },
    ],
  },
  {
    id: 'qt-203',
    quotationNumber: 'RFQ-2026-0414',
    customerId: 'cust-5',
    customerName: 'Nexus Renewable Energy',
    title: 'Inverter Mounting Sub-Assemblies',
    status: 'Draft',
    totalAmount: 18900,
    validUntil: '2026-09-01',
    createdAt: '2026-08-06',
    lineItems: [
      { id: 'li-4', partName: 'Solar Mounting Rail', material: 'Aluminum 5052-H32', thickness: '3mm', quantity: 300, unitPrice: 63, totalPrice: 18900 },
    ],
  },
];

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    sku: 'RAW-SS304-18G',
    name: '304 Stainless Steel Sheet (4ft x 8ft)',
    category: 'Sheet Metal',
    materialGrade: '304 SS (18 Gauge / 1.2mm)',
    quantity: 85,
    unit: 'Sheets',
    reorderPoint: 30,
    unitCost: 145.0,
    location: 'Rack A-04',
    lastRestocked: '2026-07-29',
  },
  {
    id: 'inv-2',
    sku: 'RAW-AL6061-250',
    name: '6061-T6 Aluminum Plate (4ft x 10ft)',
    category: 'Sheet Metal',
    materialGrade: '6061-T6 (0.25in / 6.35mm)',
    quantity: 14,
    unit: 'Sheets',
    reorderPoint: 20, // Low alert
    unitCost: 380.0,
    location: 'Rack B-01',
    lastRestocked: '2026-07-15',
  },
  {
    id: 'inv-3',
    sku: 'RAW-STEEL-A36-10G',
    name: 'A36 Hot Rolled Carbon Steel Sheet',
    category: 'Sheet Metal',
    materialGrade: 'A36 (10 Gauge / 3.4mm)',
    quantity: 120,
    unit: 'Sheets',
    reorderPoint: 40,
    unitCost: 98.5,
    location: 'Rack A-01',
    lastRestocked: '2026-08-01',
  },
  {
    id: 'inv-4',
    sku: 'HW-PEM-M6-SS',
    name: 'PEM Self-Clinching Nut M6 Stainless',
    category: 'Hardware & Fasteners',
    materialGrade: '300 Series Stainless',
    quantity: 450,
    unit: 'Pcs',
    reorderPoint: 1000, // Low alert
    unitCost: 0.45,
    location: 'Bin C-12',
    lastRestocked: '2026-06-20',
  },
  {
    id: 'inv-5',
    sku: 'GAS-NITROGEN-HP',
    name: 'High-Purity Nitrogen Laser Assist Gas',
    category: 'Consumable',
    materialGrade: 'Grade 5.0 (99.999%)',
    quantity: 3,
    unit: 'Boxes',
    reorderPoint: 5, // Low alert
    unitCost: 650.0,
    location: 'Exterior Storage Shed',
    lastRestocked: '2026-07-10',
  },
];

export const MOCK_MACHINES: Machine[] = [
  {
    id: 'mach-1',
    code: 'FIBER-LASER-01',
    name: 'TRUMPF TruLaser 5030 Fiber (6kW)',
    type: 'Laser Cutter',
    status: 'In Use',
    efficiencyRate: 96.8,
    hoursLoggedThisMonth: 184,
    lastMaintenance: '2026-07-10',
    nextScheduledMaintenance: '2026-08-20',
    assignedOperator: 'Marcus Vance',
  },
  {
    id: 'mach-2',
    code: 'PRESS-BRAKE-01',
    name: 'Bystronic Xpert Pro 150-Ton CNC Press Brake',
    type: 'CNC Press Brake',
    status: 'In Use',
    efficiencyRate: 91.2,
    hoursLoggedThisMonth: 162,
    lastMaintenance: '2026-07-18',
    nextScheduledMaintenance: '2026-08-28',
    assignedOperator: 'Alex Rivera',
  },
  {
    id: 'mach-3',
    code: 'ROBOT-WELD-01',
    name: 'Panasonic PerformArc Robotic Welding Cell',
    type: 'Robotic Welder',
    status: 'Operational',
    efficiencyRate: 98.4,
    hoursLoggedThisMonth: 140,
    lastMaintenance: '2026-07-01',
    nextScheduledMaintenance: '2026-09-01',
    assignedOperator: 'Dmitri Volkov',
  },
  {
    id: 'mach-4',
    code: 'POWDER-COAT-01',
    name: 'Gema OptiFlex Automated Powder Coating Line',
    type: 'Powder Coat Line',
    status: 'Maintenance',
    efficiencyRate: 84.5,
    hoursLoggedThisMonth: 95,
    lastMaintenance: '2026-08-06',
    nextScheduledMaintenance: '2026-08-07',
    assignedOperator: 'Elena Rostova',
  },
];

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'wrk-1',
    employeeCode: 'EMP-014',
    fullName: 'Marcus Vance',
    role: 'Supervisor',
    specialization: 'Fiber Laser Cutting & nesting',
    shift: 'Morning',
    status: 'Active',
    certifications: ['TruLaser Master Operator', 'OSHA 30 Safety'],
    hourlyRate: 38.5,
    assignedMachine: 'FIBER-LASER-01',
  },
  {
    id: 'wrk-2',
    employeeCode: 'EMP-022',
    fullName: 'Alex Rivera',
    role: 'Worker',
    specialization: 'CNC Bending & Precision Tooling',
    shift: 'Morning',
    status: 'Active',
    certifications: ['Bystronic Brake Specialist'],
    hourlyRate: 32.0,
    assignedMachine: 'PRESS-BRAKE-01',
  },
  {
    id: 'wrk-3',
    employeeCode: 'EMP-029',
    fullName: 'Dmitri Volkov',
    role: 'Worker',
    specialization: 'TIG / MIG & Robotic Welding',
    shift: 'Morning',
    status: 'Active',
    certifications: ['AWS D1.1 Structural Welding', 'Robotic Programming'],
    hourlyRate: 35.0,
    assignedMachine: 'ROBOT-WELD-01',
  },
  {
    id: 'wrk-4',
    employeeCode: 'EMP-008',
    fullName: 'Sarah Jenkins',
    role: 'Manager',
    specialization: 'Shop Floor Scheduling & Operations',
    shift: 'Morning',
    status: 'Active',
    certifications: ['Six Sigma Green Belt', 'Lean Manufacturing'],
    hourlyRate: 48.0,
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    companyName: 'Ryerson Metal Distribution',
    contactPerson: 'Ken Adams',
    email: 'kadams@ryerson.com',
    phone: '+1 (800) 555-7937',
    materialsSupplied: ['Stainless Steel', 'Aluminum 6061', 'Carbon Steel Plate'],
    averageLeadTimeDays: 3,
    rating: 4.9,
    status: 'Preferred',
  },
  {
    id: 'sup-2',
    companyName: 'McMaster-Carr Hardware Supply',
    contactPerson: 'Ordering Dept',
    email: 'orders@mcmaster.com',
    phone: '+1 (630) 600-3000',
    materialsSupplied: ['PEM Fasteners', 'Deburring Discs', 'Hardware Kits'],
    averageLeadTimeDays: 1,
    rating: 4.95,
    status: 'Preferred',
  },
  {
    id: 'sup-3',
    companyName: 'Airgas Industrial Gases',
    contactPerson: 'Sandra Bullock',
    email: 'sbullock@airgas.com',
    phone: '+1 (800) 255-2472',
    materialsSupplied: ['High-Purity Nitrogen', 'Argon Shielding Gas', 'Cutting Nozzles'],
    averageLeadTimeDays: 2,
    rating: 4.7,
    status: 'Active',
  },
];

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-501',
    poNumber: 'PO-2026-0189',
    supplierId: 'sup-1',
    supplierName: 'Ryerson Metal Distribution',
    status: 'Sent',
    totalCost: 14250,
    itemCount: 40,
    expectedDelivery: '2026-08-11',
    createdAt: '2026-08-05',
  },
  {
    id: 'po-502',
    poNumber: 'PO-2026-0190',
    supplierId: 'sup-2',
    supplierName: 'McMaster-Carr Hardware Supply',
    status: 'Received',
    totalCost: 3450,
    itemCount: 15,
    expectedDelivery: '2026-08-07',
    createdAt: '2026-08-04',
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'invc-301',
    invoiceNumber: 'INV-2026-0781',
    orderId: 'ord-106',
    customerName: 'Apex Aerospace Solutions',
    amount: 78000,
    taxAmount: 6240,
    status: 'Paid',
    dueDate: '2026-08-30',
    issuedDate: '2026-08-02',
  },
  {
    id: 'invc-302',
    invoiceNumber: 'INV-2026-0782',
    orderId: 'ord-102',
    customerName: 'Vanguard Enclosures Inc.',
    amount: 28900,
    taxAmount: 2312,
    status: 'Pending',
    dueDate: '2026-08-25',
    issuedDate: '2026-07-28',
  },
  {
    id: 'invc-303',
    invoiceNumber: 'INV-2026-0775',
    orderId: 'ord-099',
    customerName: 'Stallion Architectural Metals',
    amount: 19600,
    taxAmount: 1568,
    status: 'Overdue',
    dueDate: '2026-07-31',
    issuedDate: '2026-07-01',
  },
];

export const MOCK_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    user: 'Sarah Jenkins',
    role: 'Manager',
    action: 'Approved RFQ-2026-0413 for CNC Formed Chassis Support Ribs',
    target: 'RFQ-2026-0413',
    timestamp: '2026-08-07T14:32:00Z',
    type: 'quotation',
  },
  {
    id: 'act-2',
    user: 'Marcus Vance',
    role: 'Supervisor',
    action: 'Logged 45 finished parts on TRUMPF Fiber Laser 01',
    target: 'WO-2026-0891',
    timestamp: '2026-08-07T13:15:00Z',
    type: 'machine',
  },
  {
    id: 'act-3',
    user: 'System Bot',
    role: 'Owner',
    action: 'Low Stock Alert triggered for High-Purity Nitrogen Gas',
    target: 'GAS-NITROGEN-HP',
    timestamp: '2026-08-07T11:00:00Z',
    type: 'inventory',
  },
  {
    id: 'act-4',
    user: 'Robert Vance',
    role: 'Manager',
    action: 'Generated Invoice INV-2026-0781 (₹78,000.00)',
    target: 'INV-2026-0781',
    timestamp: '2026-08-07T09:45:00Z',
    type: 'order',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Low Stock Alert',
    message: '304 Stainless Steel Sheet quantity dropped below reorder threshold (14 left).',
    timestamp: '10 mins ago',
    read: false,
    type: 'warning',
  },
  {
    id: 'notif-2',
    title: 'Maintenance Due',
    message: 'Gema Powder Coating Line scheduled for preventative calibration today.',
    timestamp: '1 hour ago',
    read: false,
    type: 'info',
  },
  {
    id: 'notif-3',
    title: 'Payment Received',
    message: 'Apex Aerospace settled Invoice INV-2026-0781 (₹78,000.00).',
    timestamp: '3 hours ago',
    read: true,
    type: 'success',
  },
];

export const MOCK_REVENUE_CHART_DATA = [
  { month: 'Jan', revenue: 210000, target: 190000, costs: 130000 },
  { month: 'Feb', revenue: 245000, target: 210000, costs: 145000 },
  { month: 'Mar', revenue: 280000, target: 230000, costs: 160000 },
  { month: 'Apr', revenue: 260000, target: 250000, costs: 150000 },
  { month: 'May', revenue: 310000, target: 270000, costs: 175000 },
  { month: 'Jun', revenue: 325000, target: 290000, costs: 180000 },
  { month: 'Jul', revenue: 342850, target: 310000, costs: 192000 },
];

export const MOCK_PRODUCTION_STATUS_DATA = [
  { name: 'Pending Nesting', count: 12, fill: '#64748B' },
  { name: 'In Production', count: 18, fill: '#2563EB' },
  { name: 'Quality Check', count: 8, fill: '#F59E0B' },
  { name: 'Ready for Shipping', count: 6, fill: '#10B981' },
];
