import { FactoryProfile } from '@/types/marketplace';

export const VERIFIED_FACTORY_CATALOG: FactoryProfile[] = [
  {
    id: 'fac-1',
    factoryName: 'AlphaTech Precision Engineering Pvt Ltd',
    location: 'Bhosari Industrial Estate, Pune, Maharashtra',
    verifiedStatus: 'Verified',
    certifications: ['ISO 9001:2015', 'IATF 16949 Automotive', 'ZED Gold'],
    supportedMaterials: ['304 Stainless Steel', '316L Stainless Steel', '6061-T6 Aluminum', 'IS 2062 Carbon Steel'],
    machineCapabilities: ['TRUMPF TruLaser 3030 6kW Fiber', 'Amada HFE 3D 130T Press Brake', 'Panasonic 6-Axis Robot Welder', 'Nordson Powder Coating Line'],
    qualityScore: 4.95,
    onTimeDeliveryRate: 98.6,
    historicalCompletedOrders: 642,
  },
  {
    id: 'fac-2',
    factoryName: 'Apex Aerospace & Defense Fabricators',
    location: 'Peenya Industrial Area, Bengaluru, Karnataka',
    verifiedStatus: 'Verified',
    certifications: ['AS9100D Aerospace', 'ISO 9001:2015', 'NADCAP Welding'],
    supportedMaterials: ['Titanium Ti-6Al-4V', '316L Stainless Steel', 'Inconel 718', 'Aluminum 7075-T6'],
    machineCapabilities: ['DMG Mori 5-Axis CNC Mill', 'TRUMPF 10kW Fiber Laser', 'AgieCharmilles Wire EDM', 'Zeiss CMM 0.001mm QA'],
    qualityScore: 4.98,
    onTimeDeliveryRate: 99.2,
    historicalCompletedOrders: 890,
  },
  {
    id: 'fac-3',
    factoryName: 'Zenith Industrial Sheet Metal Works',
    location: 'Ambattur Industrial Estate, Chennai, Tamil Nadu',
    verifiedStatus: 'Verified',
    certifications: ['ISO 9001:2015', 'ISO 14001 Environmental', 'EN 15085 Railway'],
    supportedMaterials: ['CR4 Mild Steel', 'Galvanized Sheet (GI)', '304 Stainless Steel', 'C11000 Copper'],
    machineCapabilities: ['Bystronic ByStar 6kW Laser', 'Ermaksan 175T CNC Press Brake', 'Spot & Projection Welders', 'Zinc Nickel Plating Line'],
    qualityScore: 4.85,
    onTimeDeliveryRate: 96.4,
    historicalCompletedOrders: 518,
  },
  {
    id: 'fac-4',
    factoryName: 'Vanguard Auto-Tech Systems',
    location: 'Chakan Industrial Corridor, Pune, Maharashtra',
    verifiedStatus: 'Verified',
    certifications: ['IATF 16949:2016', 'ISO 9001:2015', 'Dun & Bradstreet Verified'],
    supportedMaterials: ['Domex 700 High-Strength Steel', '6082-T6 Aluminum', '304 Stainless Steel', 'A36 Carbon Steel'],
    machineCapabilities: ['Amada Ensis 3kW Fiber Laser', 'Trumpf TruBend 5170 Press Brake', 'ABB Robotic Tandem MIG Cell'],
    qualityScore: 4.90,
    onTimeDeliveryRate: 97.8,
    historicalCompletedOrders: 435,
  },
];
